version: 0.2
phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release      
  post_build:  
    commands:      
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket ndrest-lambda1
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:    
    - samTemplate.yaml
    - outputSamTemplate.yaml
    - stage_template_configuration.json
    - prod_template_configuration.json