Transform: AWS::Serverless-2016-10-31
Description: Creates a hello world function, with a parameter for setting the function name depending on if deployed ot Stage or Prod
Parameters:
  NameParam:    
    Type: String      
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: HelloWorld::HelloWorld.Function::FunctionHandler
      Runtime: dotnetcore2.0
      CodeUri: ./bin/Release/netcoreapp2.0/publish
      FunctionName: 
        Ref: NameParam
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            
